apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: {{ include "zookeeper-coordinator.fullname" . }}
spec:
  ports:
    {{- toYaml .Values.service.headless.ports | nindent 4 }}
  clusterIP: None
  selector:
    app: {{ include "zookeeper-coordinator.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: {{ include "zookeeper-coordinator.fullname" . }}
spec:
  ports:
    {{- toYaml .Values.service.client.ports | nindent 4 }}
  selector:
    app: {{ include "zookeeper-coordinator.fullname" . }}