apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: {{ .Values.redisMaster.replicaCount }}
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
        - name: master
          image: {{ .Values.redisMaster.image }}
          resources:
            requests:
              cpu: {{ .Values.redisMaster.cpu }}
              memory: {{ .Values.redisMaster.memory }}
          ports:
            - containerPort: {{ .Values.redisMaster.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: {{ .Values.redisSlave.replicaCount }}
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
        - name: slave
          image: {{ .Values.redisSlave.image }}
          resources:
            requests:
              cpu: {{ .Values.redisMaster.cpu }}
              memory: {{ .Values.redisMaster.memory }}
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: {{ .Values.redisMaster.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
        - name: php-redis
          image: {{ .Values.frontend.image }}
          resources:
            requests:
              cpu: {{ .Values.frontend.cpu }}
              memory: {{ .Values.frontend.memory }}
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}