apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  {{- with .Values.redisMaster.service.ports }}
  ports:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    app: redis
    role: master
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  {{- with .Values.redisMaster.service.ports }}
  ports:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    app: redis
    role: slave
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: {{ .Values.redisMaster.service.type }}
  {{- with .Values.redisMaster.service.ports }}
  ports:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    app: guestbook
    tier: frontend
---